<?php
$limit_create_mode 		= false;
$limit_create_count 	= 9999;

/** redirect or filename **/
$_CHAT_FILE		= "chat.php";
$_HOME_FILE	 	= "home.php";
$_LOGIN_FILE	= "login.php";
$_LOGOUT_FILE	= "logout.php";

/** LANGUAGE **/
$_L_HOME	= "Inicio";
$_L_PRIME	= "Prime";
$_L_PROFILE	= "Perfil";
$_L_CREATE_SERVER	= "Crear servidor";
$_L_MY_SERVERS	= "Mis servidores";
$_L_DOWNLOAD	= "Descargar";
$_L_STAFF_AREA	= "Area de Staff";
$_L_LOGOUT	= "Cerrar sesión";
$_L_NOOST_PRIME	= "Noost Prime";
$_L_NOOST_PRIME_ACTIVATED	= "Prime: Activado";
$_L_NOOST_PRIME_DISABLED	= "Prime: Desactivado";
$_L_NOOST_PRIME_BNPF	= "Compra Noost Prime por $3/mes";
$_L_NOOST_PRIME_YAY_ACTIVATED	= "Yay! Tienes una suscripción activa de Noost Prime!";
$_L_NOOST_PRIME_WHAT_CAN_I_DO	= "Qué puedo hacer?";
$_L_NOOST_PRIME_WHAT_I_WILL_GET	= "Que obtendré?";
$_L_NOOST_PRIME_F1	= "Puedes pedir una invitación personalizada para tu servidor";
$_L_NOOST_PRIME_F2	= "Tendras emoticonos (Pronto)";
$_L_NOOST_PRIME_F3	= "Oh, y tendrás una bonita insignia!";
$_L_NOOST_PRIME_F3_ALT	= "Oh, y puedes conseguir una bonita insignia!";
$_L_NOOST_PRIME_BUY_NOW	= "Comprar ahora";
$_L_SERVER	= "Servidor";
$_L_SERVER_ID	= "ID del servidor:";
$_L_SERVER_DESCRIPTION	= "Descripción del servidor:";
$_L_SERVER_SETTINGS	= "Ajustes del servidor";
$_L_JOIN_REQUESTS	= "Solicitudes de unión";
$_L_MESSAGE	= "Mensaje";
$_L_INVITED_TO_JOIN	= "Has sido invitado para unirte";
$_L_REQUEST_TO_JOIN	= "Solicitar unión";
$_L_JOIN	= "Join";
$_L_PENDING_APPROVAL	= "Aprobación pendiente";
$_L_REQUESTING	= "Solicitando...";
$_L_MEMBERS	= "Miembros";
$_L_WELCOME_TO	= "Bienvenido a";
$_L_ACCOUNT	= "Cuenta";
$_L_ACCOUNT_CHANGE_PROFILE_PICTURE	= "Cambiar foto de perfil";
$_L_ACCOUNT_IMAGE_URL	= "Link de la imagen";
$_L_CHANGE	= "Cambiar";
$_L_ACCOUNT_CHANGE_NAME	= "Cambiar nombre";
$_L_ACCOUNT_USERNAME	= "Nombre de usuario";
$_L_ACCOUNT_FIRST_NAME	= "Nombre";
$_L_ACCOUNT_LAST_NAME	= "Apellido";
$_L_ACCOUNT_CHANGE_PASSWORD	= "Cambiar contraseña";
$_L_ACCOUNT_CURRENT_PASSWORD	= "Contraseña actual";
$_L_ACCOUNT_NEW_PASSWORD	= "Nueva contraseña";
$_L_SERVER_NAME	= "Nombre del servidor";
$_L_SERVER_DESCRIPTION	= "Descripción del servidor";
$_L_WELCOME	= "Bienvenido,";
$_L_NSC	= 'Hmmm... Esto está algo vacío, no? <a href="create_room.php" class="btn btn-danger"Crea un nuevo servidor!</a>';
$_L_NSJ	= 'Hmmm... Esto está algo vacío, no? Únete al <a href="https://i.noost.xyz/Noost" class="btn btn-danger">Servidor oficial de Noost</a>';
$_L_DESCRIPTION	= "Descripción:";
$_L_SERVERS_YOU_JOINED	= "Servidores donde te has unido";
$_L_REDIRECT_TO_SERVER	= "Redireccionar a servidor";
$_L_DELETE_SERVER	= "Borrar servidor";
$_L_EDIT_PROFILE	= "Editar Perfil";
$_L_REGISTER	= "Registrar";
$_L_PASSWORD	= "Contraseña";
$_L_RE_PASSWORD	= "Repetir Contraseña";
$_L_AHA	= "Ya tienes una cuenta?";
$_L_DHA	= "No tienes una cuenta aún?";
$_L_REGISTER_NOW	= "Registrate ahora";
$_L_LOGIN_NOW	= "Iniciar sesión ahora";
$_L_LOGIN	= "Iniciar sesión";
$_L_LOGIN_TO_NOOST	= "Inicia sesión en Noost";
$_L_CSNAD	= "Cambia el nombre y la descripción de tu servidor";
$_L_MEMBERS_MANAGEMENT	= "Administración de miembros";
$_L_JOINED_AT	= "Unido en";
$_L_KICK_USER	= "Expulsar usuario";
$_L_USER_SENT_REQUEST	= "ha enviado una solicitud para unirse al servidor";
$_L_ACCEPT	= "Kickear usuario";
$_L_DENY	= "Kickear usuario";

?>
